// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetDefaultMessage provides a mock function with given fields:
func (_m *Reader) GetDefaultMessage() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessage provides a mock function with given fields: lang
func (_m *Reader) GetMessage(lang string) (string, error) {
	ret := _m.Called(lang)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(lang)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
